name: eco_trade_final
description: A new Flutter project.
publish_to: "none"

# ---------------------------------------------------------------------------
# VERSIONING
# ---------------------------------------------------------------------------
version: 1.0.0+1

# ---------------------------------------------------------------------------
# RUNTIME ENVIRONMENT
# ---------------------------------------------------------------------------
environment:
  sdk: ">=3.3.0 <4.0.0"

# ---------------------------------------------------------------------------
# DEPENDENCIES
# ---------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  # ─── Firebase (all 2024-generation plugins) ──────────────
  firebase_core:    ^3.15.1
  firebase_auth:    ^5.6.2
  cloud_firestore:  ^5.6.11
  firebase_storage: ^12.4.9
  firebase_app_check: ^0.3.0
  crypto: ^3.0.2

  # ─── Google Sign-In ──────────────────────────────────────
  google_sign_in: ^6.1.0

  # ─── OTP fields (for OTP screens) ───────────────────────
  pin_code_fields: ^8.0.0

  # ─── Utilities / device / UX ────────────────────────────
  flutter_native_splash: ^2.4.3
  url_launcher:          ^6.2.6
  image_picker:          ^1.0.8
  geolocator:            ^14.0.2
  geocoding:             ^4.0.0
  permission_handler:    ^12.0.1
  path:                  ^1.9.1
  mime:                  ^1.0.5
  shared_preferences:    ^2.2.3

# ---------------------------------------------------------------------------
# DEV-DEPENDENCIES
# ---------------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# ---------------------------------------------------------------------------
# FLUTTER ASSETS
# ---------------------------------------------------------------------------
flutter:
  uses-material-design: true

  assets:
    - assets/images/

