// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6jYhPG-GH_iPRPi38E_T5uUUWiBPmNnA',
    appId: '1:292133189032:web:a99da3e4dc89ea85e1199d',
    messagingSenderId: '292133189032',
    projectId: 'eco-trade-app',
    authDomain: 'eco-trade-app.firebaseapp.com',
    storageBucket: 'eco-trade-app.firebasestorage.app',
    measurementId: 'G-Z1P9X4P154',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB87PuJWW6DCC2qZLKf_Faje2vKjO6AUnI',
    appId: '1:292133189032:android:bd458e3795167222e1199d',
    messagingSenderId: '292133189032',
    projectId: 'eco-trade-app',
    storageBucket: 'eco-trade-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBfVWSTIYUnn2kTPUF6Ama6It5s1E1ak',
    appId: '1:292133189032:ios:87b0750842fc1b3fe1199d',
    messagingSenderId: '292133189032',
    projectId: 'eco-trade-app',
    storageBucket: 'eco-trade-app.firebasestorage.app',
    iosBundleId: 'com.example.ecoTradeFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6jYhPG-GH_iPRPi38E_T5uUUWiBPmNnA',
    appId: '1:292133189032:web:a16d80107cd8598ee1199d',
    messagingSenderId: '292133189032',
    projectId: 'eco-trade-app',
    authDomain: 'eco-trade-app.firebaseapp.com',
    storageBucket: 'eco-trade-app.firebasestorage.app',
    measurementId: 'G-7KHRD8G8C3',
  );

}