// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_jQOOfDW4uV72_5QPC84s-9KolNGdq8U',
    appId: '1:849646901741:web:08b60ba2dd28bc74d1efe4',
    messagingSenderId: '849646901741',
    projectId: 'eco-trade-dev2',
    authDomain: 'eco-trade-dev2.firebaseapp.com',
    databaseURL: 'https://eco-trade-dev2-default-rtdb.firebaseio.com',
    storageBucket: 'eco-trade-dev2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkglFWSN-DB4otmZCqYWtEboLFRAHBzrA',
    appId: '1:849646901741:android:f6f441cbd5405d90d1efe4',
    messagingSenderId: '849646901741',
    projectId: 'eco-trade-dev2',
    databaseURL: 'https://eco-trade-dev2-default-rtdb.firebaseio.com',
    storageBucket: 'eco-trade-dev2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKTYJcpSnr1Xd_vDOHXTnN7yjboMQv9r8',
    appId: '1:849646901741:ios:a8052b130e3d7a86d1efe4',
    messagingSenderId: '849646901741',
    projectId: 'eco-trade-dev2',
    databaseURL: 'https://eco-trade-dev2-default-rtdb.firebaseio.com',
    storageBucket: 'eco-trade-dev2.firebasestorage.app',
    iosBundleId: 'com.example.ecoTradeFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_jQOOfDW4uV72_5QPC84s-9KolNGdq8U',
    appId: '1:849646901741:web:661863275f5473b3d1efe4',
    messagingSenderId: '849646901741',
    projectId: 'eco-trade-dev2',
    authDomain: 'eco-trade-dev2.firebaseapp.com',
    databaseURL: 'https://eco-trade-dev2-default-rtdb.firebaseio.com',
    storageBucket: 'eco-trade-dev2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKTYJcpSnr1Xd_vDOHXTnN7yjboMQv9r8',
    appId: '1:849646901741:ios:a8052b130e3d7a86d1efe4',
    messagingSenderId: '849646901741',
    projectId: 'eco-trade-dev2',
    databaseURL: 'https://eco-trade-dev2-default-rtdb.firebaseio.com',
    storageBucket: 'eco-trade-dev2.firebasestorage.app',
    iosBundleId: 'com.example.ecoTradeFinal',
  );

}