import 'package:eco_trade_final/screens/topup_wallet_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI

// Screens
import 'splash_screen.dart';
import 'onboarding_screen1.dart';
import 'screens/user_type_selection_screen.dart';
import 'screens/collector_signup_screen.dart';
import 'screens/recycle_items_screen.dart';
import 'screens/all_set_screen.dart';
import 'screens/collector_signing_screen.dart';

import 'screens/deposit_mobile_money_screen.dart';
import 'screens/materials_collection_screen.dart';
import 'screens/business_info_screen.dart';
import 'screens/confirm_deposit_screen.dart';
import 'screens/complete_payment_screen.dart';
import 'screens/company_signup_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Recycle App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: const SplashScreen(),
      routes: {
        '/onboarding': (context) => const OnboardingScreen(),
        '/user_selection': (context) => const UserTypeSelectionScreen(),
        '/collector_signup': (context) => const CollectorSignUpScreen(),
        '/recycle_items': (context) => const RecycleItemsScreen(),
        '/all_set': (context) => const AllSetScreen(),
        '/collector_signing': (context) => const CollectorSigningScreen(),
        '/topUpWallet': (context) => const TopUpWalletScreen(),
        '/depositMobileMoney': (context) => const DepositMobileMoneyScreen(),
        '/materialsCollection': (context) => const MaterialsCollectionScreen(),
        '/businessInfo': (context) => const BusinessInfoScreen(),
        '/confirmDeposit': (context) => const ConfirmDepositScreen(
          mobileNumber: 'MTN – 055 *** 1234',
          mobileProvider: 'MTN',
          amount: 200,
          commission: 0.0,
        ),
        '/completePayment': (context) => const CompletePaymentScreen(),
        '/company_signup': (context) => const CompanySignUpScreen(),
        '/home': (context) => const HomeScreen(),
      },
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home')),
      body: const Center(child: Text('Welcome to Home Screen')),
    );
  }
}
